Update run-open-page-test.yml

diff --git a/.github/workflows/run-open-page-test.yml b/.github/workflows/run-open-page-test.yml
--- a/.github/workflows/run-open-page-test.yml
+++ b/.github/workflows/run-open-page-test.yml
@@ -23,16 +23,22 @@ jobs:
           pip install -r requirements.txt
           pip install selenium
 
+     # - name: Install Google Chrome
+      #  run: |
+       #   wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+        #  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
+         # sudo apt-get update
+          #sudo apt-get install -y google-chrome-stable || { echo "Failed to install Google Chrome."; exit 1; }
+          #if [ ! -x "$(command -v google-chrome)" ]; then
+           # echo "Google Chrome installation failed. Binary not found."
+          #exit 1
+          #fi
+
       - name: Install Google Chrome
         run: |
-          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
-          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
+          wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo apt-get update
-          sudo apt-get install -y google-chrome-stable || { echo "Failed to install Google Chrome."; exit 1; }
-          if [ ! -x "$(command -v google-chrome)" ]; then
-            echo "Google Chrome installation failed. Binary not found."
-          exit 1
-          fi
+          sudo apt-get install -y /tmp/chrome.deb
 
       - name: Install ChromeDriver
         run: |
