Update run-open-page-test.yml

diff --git a/.github/workflows/run-open-page-test.yml b/.github/workflows/run-open-page-test.yml
--- a/.github/workflows/run-open-page-test.yml
+++ b/.github/workflows/run-open-page-test.yml
@@ -28,10 +28,10 @@ jobs:
           wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
           sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
           sudo apt-get update
-          sudo apt-get install -y google-chrome-stable
-          if [ ! -f /usr/bin/google-chrome ]; then
+          sudo apt-get install -y google-chrome-stable || { echo "Failed to install Google Chrome."; exit 1; }
+          if [ ! -x "$(command -v google-chrome)" ]; then
             echo "Google Chrome installation failed. Binary not found."
-            exit 1
+          exit 1
           fi
 
       - name: Install ChromeDriver
